name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_INSTANCE_IP }} >> ~/.ssh/known_hosts

      - name: Set correct permissions
        run: |
          ssh ${EC2_USERNAME}@${EC2_INSTANCE_IP} 'sudo chmod -R 755 /var/www/html'
          ssh ${EC2_USERNAME}@${EC2_INSTANCE_IP} 'sudo chown -R ${EC2_USERNAME}:${EC2_USERNAME} /var/www/html'

      - name: Deploy via rsync
        run: |
          sudo rsync -avz --exclude '.git' --exclude '.github' * ${EC2_USERNAME}@${EC2_INSTANCE_IP}:/var/www/html/
          ssh ${EC2_USERNAME}@${EC2_INSTANCE_IP} 'sudo systemctl restart apache2'
