name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Apache on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${EC2_USERNAME}@${EC2_INSTANCE_IP} 'sudo apt update'
          ssh -o StrictHostKeyChecking=no ${EC2_USERNAME}@${EC2_INSTANCE_IP} 'sudo apt install -y apache2'

      - name: Deploy via SSH
        run: |
          sudo scp -r * ${EC2_USERNAME}@${EC2_INSTANCE_IP}:/var/www/html
          ssh -o StrictHostKeyChecking=no ${EC2_USERNAME}@${EC2_INSTANCE_IP} 'sudo systemctl restart apache2'
